server:
  port: 8081
  servlet:
    context-path: /api/v1
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/BeClassyShop
    username: root
    password: Binh!190998
  jpa:
    hibernate:
      ddl-auto: update  # ho?c create, create-drop, validate, tï¿½y theo nhu c?u c?a b?n
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
springdoc:
  swagger-ui:
    path: /swagger-ui.html
